AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: url-shortner-uday

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:

  UrlApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UrlApi
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Header: Authorization
      MethodSettings:
        - LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
          ResourcePath: "/*"
          HttpMethod: "*"

  UrlShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: url-shortner/app.lambdaHandler
      Runtime: nodejs22.x
      Architectures: [x86_64]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlTableUday
      Events:
        ShortenUrl:
          Type: Api
          Properties:
            Path: /get-url-shortner
            Method: post
            RestApiId: !Ref UrlApi
            Auth:
              Authorizer: LambdaTokenAuthorizer  
        RedirectUrl:
          Type: Api
          Properties:
            Path: /short/{id}
            Method: get
            RestApiId: !Ref UrlApi
            
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTableUday
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - url-shortner/app.ts
        Minify: true
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/client-dynamodb'

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: auth/auth.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          JWT_SECRET: "123456"
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - auth/auth.ts
        Minify: true
        Target: es2020
        Sourcemap: true

  UrlTableUday:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlTable-uday-auth
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: 'Base URL for the API Gateway'
    Value: !Sub 'https://${UrlApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
